---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 18/11/7 20:31
---

require("UI.UIBasePanel")
require("UI.AdjutantPanel.AdjutantItem.UIAdjutantItem");

UIDormFavorabilityPanelV2 = class("UIDormFavorabilityPanelV2", UIBasePanel);
UIDormFavorabilityPanelV2.__index = UIDormFavorabilityPanelV2;

UIDormFavorabilityPanelV2.mView = nil;
UIDormFavorabilityPanelV2.mGunId = 0;

function UIDormFavorabilityPanelV2:ctor()
    UIDormFavorabilityPanelV2.super.ctor(self);
end

function UIDormFavorabilityPanelV2.Open(currentGun, selectedCount)
    self = UIDormFavorabilityPanelV2;

end

function UIDormFavorabilityPanelV2.Close()
    UIManager.CloseUI(UIDef.UIDormFavorabilityPanelV2);
end

function UIDormFavorabilityPanelV2.Hide()
    self = UIDormFavorabilityPanelV2;
    self:Show(false);
end

function UIDormFavorabilityPanelV2.Init(root, data)
    UIDormFavorabilityPanelV2.super.SetRoot(UIDormFavorabilityPanelV2, root);

    UIDormFavorabilityPanelV2.mData = data;
    UIDormFavorabilityPanelV2.mView = UIDormFavorabilityPanelV2View;
    UIDormFavorabilityPanelV2.mView:InitCtrl(root);

end


function UIDormFavorabilityPanelV2.OnInit()
    self = UIDormFavorabilityPanelV2;

    UIUtils.GetButtonListener(self.mView.mBtn_Close.gameObject).onClick = self.OnReturnClick;

end


function UIDormFavorabilityPanelV2:ShowRadar()
    local last = NetCmdDormDataV2.CommanderLastCharm;
    local current = NetCmdDormDataV2.CommanderCharm;

    self.mView.mRadarBefore:InitGraphParams(0.2,1000);
    self.mView.mRadarBefore:LoadPrevValues({last[0],last[1],last[2],last[3]});
    self.mView.mRadarAfter:LoadPrevValues({last[0],last[1],last[2],last[3]});

    TimerSys:DelayCall(0.5, function ()
        self.mView.mRadarAfter:SetValues({current[0],current[1],current[2],current[3]});
        self.mView.mRadarBefore:SetValues({last[0],last[1],last[2],last[3]});

        NetCmdDormDataV2:SyncLastCharm();
    end)
end


function UIDormFavorabilityPanelV2.OnReturnClick(gameObject)
    self = UIDormFavorabilityPanelV2;
    self.Close();
end

function UIDormFavorabilityPanelV2.OnShow()
    self = UIDormFavorabilityPanelV2;

    self:ShowRadar();
end

function UIDormFavorabilityPanelV2.OnRelease()
    self = UIDormFavorabilityPanelV2;
    
end
