---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 18/10/23 11:17
---

--通用枪相关逻辑处理
--For ins : 排序

CommonGunUtils = {};
local this = CommonGunUtils;

CommonGunUtils.sortKeyState = 0;
CommonGunUtils.sortAscOrder = 0;

--枪按照某种特定状态排序
function CommonGunUtils.SortGunByKeyState(isSortAD, keyState, gunList)
    CommonGunUtils.sortAscOrder = isSortAD;
    CommonGunUtils.sortKeyState = keyState;
    table.sort(gunList, CommonGunUtils.SortSubFunction);
end

--排序子函数
function CommonGunUtils.SortSubFunction(gunAItem, gunBItem)
    --local gunA = gunAItem.GunInfo;
    --local gunB = gunBItem.GunInfo;

    local gunATableData = TableData.GetGunData(gunAItem.stc_gun_id);
    local gunBTableData = TableData.GetGunData(gunBItem.stc_gun_id);

    if CommonGunUtils.sortKeyState == 1 then
        if (gunAItem.level == gunBItem.Level) then
            return false;
        else
            if CommonGunUtils.sortAscOrder then
                return (gunAItem.level > gunBItem.level);
            else
                return (gunAItem.level < gunBItem.level);
            end
        end
    end

    if CommonGunUtils.sortKeyState == 2 then
    end

    if CommonGunUtils.sortKeyState == 3 then
    end

    if CommonGunUtils.sortKeyState == 4 then
        if (gunATableData.rank == gunBTableData.rank) then
            return false;
        else
            if CommonGunUtils.sortAscOrder then
                return (gunATableData.rank > gunBTableData.rank);
            else
                return (gunATableData.rank < gunBTableData.rank)
            end
        end
    end

    if CommonGunUtils.sortKeyState == 5 then
        if (gunAItem.hp == gunBItem.hp) then
            return false;
        else
            if CommonGunUtils.sortAscOrder then
                return (gunAItem.hp > gunBItem.hp);
            else
                return (gunAItem.hp < gunBItem.hp);
            end
        end
    end

    if CommonGunUtils.sortKeyState == 6 then
        if (gunAItem.team_id == gunBItem.team_id) then
            return false;
        else
            if CommonGunUtils.sortAscOrder then
                return (gunAItem.team_id > gunBItem.team_id);
            else
                return (gunAItem.team_id < gunBItem.team_id);
            end
        end
    end

    if CommonGunUtils.sortKeyState == 7 then
        if (gunAItem.wear == gunBItem.wear) then
            return false;
        else
            if CommonGunUtils.sortAscOrder then
                return (gunAItem.wear < gunBItem.wear);
            else
                return (gunAItem.wear > gunBItem.wear);
            end
        end
    end

    return false;
end

