---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 18/11/7 20:31
---

require("UI.UIBasePanel")
require("UI.ExpeditionSettlementPanel.UIExpeditionSettlementPanelView");


UIExpeditionSettlementPanel = class("UIExpeditionSettlementPanel", UIBasePanel);
UIExpeditionSettlementPanel.__index = UIExpeditionSettlementPanel;

UIExpeditionSettlementPanel.mData = nil;
UIExpeditionSettlementPanel.mView = nil;

function UIExpeditionSettlementPanel:ctor()
    UIExpeditionSettlementPanel.super.ctor(self);
end

function UIExpeditionSettlementPanel.Open()
    UIExpeditionSettlementPanel.OpenUI(UIDef.UIExpeditionSettlementPanel);
end

function UIExpeditionSettlementPanel.Close()
    UIManager.CloseUI(UIDef.UIExpeditionSettlementPanel);
end

function UIExpeditionSettlementPanel.Init(root, data)
    self = UIExpeditionSettlementPanel;
    self.mData = data;
    self:SetRoot(root);
end


function UIExpeditionSettlementPanel.OnInit()
    self = UIExpeditionSettlementPanel;

    self.mView = UIExpeditionSettlementPanelView;
    self.mView:InitCtrl(self.mUIRoot);
    self.mView:InitData(self.mData);

    self:InitResources();

    UIUtils.GetButtonListener(self.mView.mBtn_TopInformation_Return.gameObject).onClick = self.OnReturnClick;
    UIUtils.GetButtonListener(self.mView.mBtn_ExpeditionTask_ExpeditionTaskAward_CancelExpedition.gameObject).onClick = self.OnReturnClick;
    UIUtils.GetButtonListener(self.mView.mBtn_ExpeditionTask_ExpeditionTaskAward_GoExpedition.gameObject).onClick = self.OnGoAgainClicked;
end

function UIExpeditionSettlementPanel:InitResources()
    self.mView.mText_TopInformation_Coin_BodyCoin_CoinAmount.text = GlobalData.stamina_ext;
    self.mView.mText_TopInformation_Coin_GoldCoin_CoinAmount.text = GlobalData.cash;
    local data = NetCmdItemData:GetNormalItem(201);
	if(data ~= nil) then
		self.mView.mText_TopInformation_Coin_TokenCoin_CoinAmount.text= data.item_num;
	else
		self.mView.mText_TopInformation_Coin_TokenCoin_CoinAmount.text = 0;
    end
end


function UIExpeditionSettlementPanel.OnShow()
    self = UIExpeditionSettlementPanel;
end

function UIExpeditionSettlementPanel.OnRelease()
    self = UIExpeditionSettlementPanel;

    self.mTypeItemList = {};
end

function UIExpeditionSettlementPanel.OnGoAgainClicked(gameobj)
    self = UIExpeditionSettlementPanel;

    NetCmdExpeditionData:SendDungeonDispatchMission(self.mData.cmd.mission_id,self.mData.gunIds,self.OnGoExpeditionCallback);
    NetCmdExpeditionData:OnResultPanelClose();
    NetCmdExpeditionData:TrySendNextResult();

    self.Close();
end

function UIExpeditionSettlementPanel.OnGoExpeditionCallback(ret)
    self = UIExpeditionSettlementPanel;
	
	if ret == CS.CMDRet.eSuccess then
        gfdebug("远征开始成功");
        MessageSys:SendMessage(CS.GF2.Message.ExpeditionEvent.ExpeditionGoAgain,nil);
	else
		gfdebug("远征开始失败");
	end	
end

function UIExpeditionSettlementPanel.OnReturnClick(gameobj)	
    self = UIExpeditionSettlementPanel;
    NetCmdExpeditionData:OnResultPanelClose();
    NetCmdExpeditionData:TrySendNextResult();
	self.Close();
end

