---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 6.
--- DateTime: 18/9/9 23:15
---
require("UI.UIBaseCtrl")

UIChrInfoItemV2 = class("UIChrInfoItemV2", UIBaseCtrl);
UIChrInfoItemV2.__index = UIChrInfoItemV2;



function UIChrInfoItemV2:ctor()
    UIChrInfoItemV2.super.ctor(self);
end

function UIChrInfoItemV2:InitCtrl(parent)
    local prefab = ResSys:GetUIGizmos("UICommonFramework/ComChrEnemyInfoItemV2.prefab");
    local obj = instantiate(prefab, parent); 

    self:SetRoot(obj.transform);

    self.mIcon = self:GetImage("GrpContent/GrpSkillIcon/GrpIcon/Img_Icon")
    self.m_NameText = self:GetText("GrpContent/GrpText/TextTittle/Text_Name")
    self.m_LayerNumText = self:GetText("GrpContent/GrpText/TextTittle/Text_LayerNum")
    self.m_DescriptionText = self:GetText("GrpContent/GrpText/Text_Dscription")
end


function UIChrInfoItemV2:SetData(skillId,index)
    local skillData = TableData.listBattleSkillDatas:GetDataById(skillId)
    self.m_NameText.text = skillData.name.str;   
    self.m_DescriptionText.text = skillData.description.str
    self.m_LayerNumText.text = string_format(TableData.GetHintById(30030), index)
    self.mIcon.sprite = IconUtils.GetSkillIconSprite(skillData.icon)       
end

