---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 6.
--- DateTime: 18/9/9 23:15
---
require("UI.UIBaseCtrl")

UISkillIconCtrl = class("UISkillIconCtrl", UIBaseCtrl);
UISkillIconCtrl.__index = UISkillIconCtrl;


function UISkillIconCtrl:ctor()
    UISkillIconCtrl.super.ctor(self);
end

function UISkillIconCtrl:InitCtrl(root,parent)
    self:SetRoot(root);

    root:SetParent(parent,false);
    self.m_SkillIcon =self:GetImage("GrpNor/Img_Icon");
    self.m_RootBtn = self:GetSelfButton();
end


function UISkillIconCtrl:InitData(skillData,gunData,weapon)
    self. m_SkillData = data;
    --self.m_SkillIcon.sprite = IconUtils.GetSkillIconSprite(data.Data.icon); 

    if(gunData~= nil) then
        local weaponId = gunData.weapon_default;
        if(weapon > 0) then
            weaponId = weapon;
        end
        
        self.m_SkillIcon.sprite = IconUtils.GetSkillIconByAttr(skillData.Data.icon, skillData.Data.icon_attr_type, weaponId)
    else

        self.m_SkillIcon.sprite = IconUtils.GetSkillIconSprite(skillData.Data.icon); 

    end
end

function UISkillIconCtrl:SetData(data)
    --todo
   -- self.m_SkillIcon.sprite = IconUtils.GetSkillIconSprite(data.icon);
end

function UISkillIconCtrl:SetSelected(value)       
    self.m_RootBtn.interactable = (not value);
end
