---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 18/11/12 12:18
---

UICNWords = {};

UICNWords.Caution = "CAUTION";
UICNWords.CannotReplace = "当前人形忙碌，无法替换！";
UICNWords.CannotDismantling = "当前人形忙碌/在梯队中，无法替换！";
UICNWords.OverGunLimit = "超过添加人形数量！";
UICNWords.IfReplaceCurTeam = "是否将该梯队载具与当前梯队载具替换？";
UICNWords.IfReplaceSure = "使用该载具会解散该载具原本所在梯队。是否确定？";
UICNWords.IfDismissTeam = "卸除载具会解散当前梯队，是否确定？";
UICNWords.PartIsOccupy = "装备中";
UICNWords.PartIsOverweight = "载重不足";
UICNWords.EquipOn = "装备于";
UICNWords.EquipUnable = "无法装备";
UICNWords.EquipApplyGun = "适用人形：";
UICNWords.SimCombatLockedType2 = "完成前置作战后解锁";
UICNWords.LevelUpMaterialIsNull = "强化素材不足！";
UICNWords.LevelUpMaterialBeyondLimit = "超过素材上限！";
UICNWords.AddedNum = "已添加：";
UICNWords.EquipLevelMax = "装备已强化至最大等级！";
UICNWords.InsufficientCash = "Cash不足！";
UICNWords.InsufficientEquipmentOrItem = "同类型装备不足！";
UICNWords.UnableUpGrade = "同类型装备/卷轴不足，无法升阶！";
UICNWords.UpGradeAddedOver = "超过需要的素材上限！";
UICNWords.UpGradeMax = "已强化到最大星级！";
UICNWords.Calibration1st = "请先执行校调";
UICNWords.None = "无";
UICNWords.InsufficientCalibrationCostItem = "校调所需素材不足！";
UICNWords.UnSelectedCaliMaterial = "未选择校准素材！";
UICNWords.NonePreCalibration = "空的预选校准！";
UICNWords.NickName = "昵称：";
UICNWords.GuildName = "工会名称：";
UICNWords.UID = "UID："
UICNWords.Level = "Level："

