---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 6.
--- DateTime: 18/9/11 16:53
---
require("UI.UIBaseView")

UI_TeamSelTempView = class("UI_TeamSelTempView", UIBaseView);
UI_TeamSelTempView.__index = UI_TeamSelTempView;

UI_TeamSelTempView.mGrid_FormationSelect = nil;
UI_TeamSelTempView.mButton_IntoBattle = nil;
UI_TeamSelTempView.mButton_ExitStage = nil;

--构造
function UI_TeamSelTempView:ctor()
    UI_TeamSelTempView.super.ctor(self);
end

--初始化
function UI_TeamSelTempView:InitCtrl(root)

    self:SetRoot(root);

    self.mGrid_FormationSelect = self:FindChild("FormationList/FormationDetail/Team/List");
    self.mButton_IntoBattle = self:GetButton("ConfirmBtn");
    self.mButton_ExitStage = self:GetButton("ExitStage");
end